### ISSUE TITLE
Changing Selection Color

### ISSUE THREAD

**Issue by cevarief** [aFarkas/remote-list#3]
How to change hover selection and the list background color?

**Comment by aFarkas** [comment]
For native datalist this can't be done x-browser. For the polyfilled/enhanced version it is simple.

``` css
.datalist-polyfill .datalist-box ul {
    background-color: #aaa;
}
.datalist-polyfill .datalist-box .active-item {
    background-color: #a66;
}
```

Just curious: Do you think this needs to be documented. Because it's quite simple to look yourself by using the devtools???
